services:
    backend:
        build: ./backend/
        restart: unless-stopped
        stdin_open: true
        tty: true
        env_file: ".env"
        ports:
            - 8181:8181
        volumes:
            - ./backend/volume:/backend/volume
        networks:
            - app-network

    ngrok:
        image: ngrok/ngrok:latest
        restart: unless-stopped
        environment:
            - NGROK_AUTHTOKEN=${NGROK_AUTH_TOKEN}
            - NGROK_DOMAIN=${NGROK_DOMAIN}
        ports:
            - "4040:4040"
        command: http --domain=${NGROK_DOMAIN} backend:8181
        depends_on:
            - backend
        networks:
            - app-network

networks:
    app-network:
        driver: bridge